
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import CosmosApp from "@/context/WalletProvider";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/sidebar";
import StoreProvider from './storeProvider'
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  style: "normal",
});
export const metadata: Metadata = {
  title: "INJ Staking",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-dark-900">
      <body
        className={`${poppins.className} bg-dark-900 text-white h-full w-full`}
      >
        <StoreProvider>
          <CosmosApp>
            <main className="flex">
              <div className="fixed top-0 left-0 z-50 w-full">
                <Navbar />
              </div>
              <div className="fixed top-0 left-0 z-40 h-full pt-[88px]">
                <Sidebar />
              </div>
              <div className="pl-[358px] pt-[88px] h-full w-full">
                <div className="pt-6 pb-0 px-6 h-full w-full overflow-y-scroll no-scrollbar mb-10">
                  {children}
                </div>
              </div>
              <ToastContainer />
            </main>
          </CosmosApp>
        </StoreProvider>
        
      </body>
    </html>
  );
}
